<?php

namespace Database\Seeders;

use App\Models\DocumentType;
use Illuminate\Database\Seeder;

class DocumentTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            [
                'name' => 'Aadhaar Card',
                'code' => 'aadhar_card',
                'description' => 'Upload Aadhaar Card (Front and Back side copies required).',
                'is_required' => false,
                'has_front_back' => true,
                'allow_multiple' => false,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 10240,
                'sort_order' => 1,
                'status' => 'active',
            ],
            [
                'name' => 'PAN Card',
                'code' => 'pan_card',
                'description' => 'Upload clear copy of PAN Card.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => false,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 10240,
                'sort_order' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Udyam Certificate',
                'code' => 'udyam_certificate',
                'description' => 'Upload MSME / Udyam Registration Certificate.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => false,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 10240,
                'sort_order' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'GST Certificate',
                'code' => 'gst_certificate',
                'description' => 'Upload GST Registration Certificate.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => false,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 10240,
                'sort_order' => 4,
                'status' => 'active',
            ],
            [
                'name' => 'Caste Certificate',
                'code' => 'caste_certificate',
                'description' => 'Upload Caste / Category Certificate if applicable.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => false,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 10240,
                'sort_order' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Ration Card',
                'code' => 'ration_card',
                'description' => 'Upload copy of Ration Card.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => false,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 10240,
                'sort_order' => 6,
                'status' => 'active',
            ],
            [
                'name' => 'Rent Agreement / Light Bill / Vera Poch',
                'code' => 'rent_light_bill_tax',
                'description' => 'Upload Rent Agreement, Electricity Bill or Tax Receipt.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => true,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 10240,
                'sort_order' => 7,
                'status' => 'active',
            ],
            [
                'name' => 'L.C. (Leaving Certificate)',
                'code' => 'leaving_certificate',
                'description' => 'Upload School or College Leaving Certificate.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => false,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 10240,
                'sort_order' => 8,
                'status' => 'active',
            ],
            [
                'name' => 'Marksheet',
                'code' => 'marksheet',
                'description' => 'Upload educational marksheets or degree certificates.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => true,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 10240,
                'sort_order' => 9,
                'status' => 'active',
            ],
            [
                'name' => 'Photo',
                'code' => 'photo',
                'description' => 'Upload recent passport size photograph.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => false,
                'allowed_file_types' => ['jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 5120,
                'sort_order' => 10,
                'status' => 'active',
            ],
            [
                'name' => 'ITR with BL',
                'code' => 'itr_with_balance_sheet',
                'description' => 'Upload Income Tax Returns with Balance Sheet and P&L.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => true,
                'allowed_file_types' => ['pdf', 'xlsx', 'xls', 'doc', 'docx', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 20480,
                'sort_order' => 11,
                'status' => 'active',
            ],
            [
                'name' => 'Bank Statement',
                'code' => 'bank_statement',
                'description' => 'Upload 6-12 months Bank Statements.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => true,
                'allowed_file_types' => ['pdf', 'xlsx', 'xls', 'csv', 'doc', 'docx', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 20480,
                'sort_order' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Quotation - Asset',
                'code' => 'quotation_asset',
                'description' => 'Upload asset / machinery quotation or invoice.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => true,
                'allowed_file_types' => ['pdf', 'xlsx', 'xls', 'doc', 'docx', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 20480,
                'sort_order' => 13,
                'status' => 'active',
            ],
            [
                'name' => 'Quotation - Stock',
                'code' => 'quotation_stock',
                'description' => 'Upload stock purchase quotation or estimates.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => true,
                'allowed_file_types' => ['pdf', 'xlsx', 'xls', 'doc', 'docx', 'jpg', 'jpeg', 'png'],
                'max_file_size_kb' => 20480,
                'sort_order' => 14,
                'status' => 'active',
            ],
            [
                'name' => 'Subsidy Application',
                'code' => 'subsidy_application',
                'description' => 'Upload Subsidy Application copy or acknowledgement.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => false,
                'allowed_file_types' => ['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'],
                'max_file_size_kb' => 10240,
                'sort_order' => 15,
                'status' => 'active',
            ],
            [
                'name' => 'Project Report',
                'code' => 'project_report',
                'description' => 'Upload detailed Project Report (DPR).',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => false,
                'allowed_file_types' => ['pdf', 'doc', 'docx', 'xlsx', 'xls'],
                'max_file_size_kb' => 20480,
                'sort_order' => 16,
                'status' => 'active',
            ],
            [
                'name' => 'CMA',
                'code' => 'cma_report',
                'description' => 'Upload CMA Report & financial projections.',
                'is_required' => false,
                'has_front_back' => false,
                'allow_multiple' => false,
                'allowed_file_types' => ['pdf', 'xlsx', 'xls'],
                'max_file_size_kb' => 20480,
                'sort_order' => 17,
                'status' => 'active',
            ],
        ];

        foreach ($types as $type) {
            DocumentType::updateOrCreate(['code' => $type['code']], $type);
        }
    }
}
